### PR TITLE
adding Spring framework to the list

### PR DESCRIPTION
**Pull request by jcchv**
https://github.com/jcchv/Spring-JavaFX

Spring Boot is a really good option to integrate with a Java Fx Project 

:smiley:

### CODE REVIEW

**Comment by mhrimaz** [comment]
This is a relatively new project and it needs more documentation and description to be useful for everybody when it becomes ready, it will merge into the list.
Thanks.

**Comment by aalmiray** [comment]
@jcchv: a few things that will make it easier for other people to understand the motivation of the project and how to build it:

 . add a README.md (markdown) or README.adoc (asciidoc) file explaining the basics of the project, its design and pointers to some examples (wiki perhaps?)
 . add a `.gitignore` file marking .gradle, .idea, out, and META-INF as ignored. Also remove these files from the git index.
 . add a BUILD.[md|adoc] and/or INSTALLING.[md|adoc] file listing instructions on how to build and run the project.
 . choose a license for the code, such as an Open Source license.

This particular project appears to be a basic example on how to combine JavaFX and spring-boot. Currently the AwesomeJavaFX repository does not provide entries of this type, opting for Tutorials (code with detailed explanations) or Real World examples (applications that can be downloaded and used for a particular purpose).

All this being said, like @mhrimaz mentioned, this project may need a few more iterations and some additional time to mature. It would be great if you can keep updating the code and try out new things 😄

**Comment by jcchv** [comment]
Thank you guys, i'm barely new at github and JavaFX Projects, @aalmiray Thank you for the advices  i will work more in this project till get something like a template ready to work with it

:smile:

**Comment by aalmiray** [comment]
No worries, it takes you a couple of times to get it right. Don't get discouraged if you don't get a `yes` at the first try. Adapt and give it another go 😄

**Comment by goxr3plus** [comment]
@jcchv  It seems there's no more support for that library ...

**Comment by AlmasB** [comment]
Based on comments above, it appears the library is no longer maintained.

**Pull request closed without merging**
