### PR TITLE
AsyncFX - An asynchronous library

### PR DESCRIPTION
**Pull request by RyanSusana**
AsyncFX is a library created by me that I use in my JavaFX projects.

It helps me **easily** create async calls. It comes with a nice DSL, inspired by the Stream API and Android AsyncTasks

https://github.com/RyanSusana/AsyncFX

### CODE REVIEW

**Comment by RyanSusana** [comment]
I am aware that this library is new.

**Comment by goxr3plus** [comment]
@RyanSusana  Beautiful thank you so much :)!!!

**Comment by AlmasB** [comment]
@RyanSusana Many thanks for this addition. We're currently updating the contribution guidelines and keeping all projects in alphabetical order. Please can provide the following details:

- Does the latest commit build -- it seems CI is failing?
- Could you add your project to maintain the alphabetical order please. 
- Also I was wondering if your project is better suited under Libraries, since the description states it's a library?

Cheers!

**Comment by Hakky54** [comment]
Hi @RyanSusana this PR is open for quite some time, but it would be nice if we could merge it. Any idea whether it is possible to address the remarks of @AlmasB to your repo? Not quite sure whether you are still maintaining AsyncFX, seems like a cool project.

**Pull request closed without merging**
