### PR TITLE
Updated Real World, new Project Ideas section

### PR DESCRIPTION
**Pull request by JerJohn15**
- added a new tutorial link
- created "Project Ideas" section
- updated "real world examples" section
- Fixed formatting

### CODE REVIEW

**Comment by mhrimaz** [comment]
Unfortunately this repo is dedicated to JavaFX, so please add related stuff. Thanks @JerJohn15

**Comment by JerJohn15** [comment]
@mhrimaz 

The only reason why I added some of these was because they could potentially be used for Java FX if someone wanted to re-engineer them. But I'll do as you suggested.

**Comment by mhrimaz** [comment]
@JerJohn15 
Thank you for your contribution. There is another curated list that java developer in general can use it in any project. You can contribute to that project : https://github.com/akullpp/awesome-java

**Comment by JerJohn15** [comment]
@mhrimaz Your welcome. Thanks for the link.

**Pull request closed without merging**
